// <auto-generated />
namespace OWWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Changedranfromshorttoushorttomatchoverwatchnetresponse : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Changedranfromshorttoushorttomatchoverwatchnetresponse));
        
        string IMigrationMetadata.Id
        {
            get { return "201703120340589_Changed ran from short to ushort to match overwatch.net response."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
