// <auto-generated />
namespace OWWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ChangedushortbacktoshortIthinkitwasbreakingazuresql : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangedushortbacktoshortIthinkitwasbreakingazuresql));
        
        string IMigrationMetadata.Id
        {
            get { return "201703120354352_Changed ushort back to short, I think it was breaking azure sql."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
