// <auto-generated />
namespace OWWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Addinglocationtoapalyer : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Addinglocationtoapalyer));
        
        string IMigrationMetadata.Id
        {
            get { return "201703120225555_Adding location to a palyer."; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
