// <auto-generated />
namespace OWWeb.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Fixedforeignkeyforrankhistory : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Fixedforeignkeyforrankhistory));
        
        string IMigrationMetadata.Id
        {
            get { return "201703120944412_Fixed foreign key for rankhistory"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
